name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build Docker image
        run: docker build -t jishnu1515/nextjs-app .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to Docker Hub
        run: docker push jishnu1515/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull jishnu1515/nextjs-app:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container || true
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name nextjs-app-container jishnu1515/nextjs-app:latest
